GitHub CI actions
artipie/maven-resolver-http3-plugin pull request #5
Opened 2023-11-02 08:47 UTC by ChGen

GitHub CI actions + `.gitattributes`

2023-11-02 10:57 UTC, ChGen commented
@dgarus , please review.

2023-11-03 08:02 UTC, dgarus requested changes

2023-11-03 08:02 UTC, dgarus commented on .github/workflows/release.yml
> +          java-version: 8
why 8?

2023-11-03 08:02 UTC, dgarus commented on .github/workflows/release.yml
> +      - '*'
Does `*` mean for any tag?

2023-11-03 09:17 UTC, ChGen commented
@dgarus , please review.

2023-11-03 09:58 UTC, dgarus approved these changes

2023-11-03 12:23 UTC, ChGen commented
@olenagerasimova , please review.

2023-11-03 14:17 UTC, olenagerasimova approved these changes
thanks

2023-11-03 14:22 UTC, merged